---
title: "Interpolation"
subtitle: "Numerical Analysis"
author: "Urbain Vaes"
institute: "NYU Paris"

format:
    revealjs:
        theme: [default, ../config/custom.scss]
        width: 1600
        height: 900
        chalkboard: false
        transition: convex
        progress: true
        touch: true
        keyboard: true
        mouse-wheel: true
        controls: true
        controls-layout: edges
        navigation-mode: vertical
        callout-appearance: default
        slide-number: h.v
        eval: false
        echo: true
        preview-links: auto
        toc: false
        embed-resources: true

revealjs-plugins:
  - verticator
  - pointer

bibliography: ../biblio/scientific_computing.bib
link-citations: true
csl: ../biblio/elsevier-harvard.csl

editor:
    render-on-save: true

jupyter: julia-1.10
execute:
  freeze: auto
  warning: false
  error: false
  keep-ipynb: false

---

```{julia}
#| echo: false
#| eval: true
#| code-fold: true
#| code-line-numbers: false

import Plots
using LaTeXStrings
# Plots.pgfplotsx()

Plots.default(fontfamily="Computer Modern",
              titlefont = "Computer Modern",
              legendfont = "Computer Modern",
              titlefontsize=20,
              xlabelfontsize=20,
              ylabelfontsize=20,
              legendfontsize=16,
              xtickfontsize=16,
              ytickfontsize=16,
              linewidth=4,
              markersize=7,
              framestyle=:box,
              grid=false,
              background_color=:transparent,
              foreground_color=:black,
              top_margin=5Plots.mm,
              bottom_margin=12Plots.mm,
              left_margin=12Plots.mm,
              right_margin=5Plots.mm,
)
;
```


## Existence and uniqueness {.smaller}

{{< include ../config/_macros_revealjs.tex >}}
{{< include ../config/_macros_colors.tex >}}

::: {.callout-note icon=false}
## Theorem (Existence and uniqueness)
Given data $x_0 < x_1< \dotsc < x_n$ and $y_0, \dotsc, y_n$,
there **exists** a **unique** $p \in \mathcal P_n$ such that
$$
\forall i \in \{0, \dotsc, n\}, \qquad p(x_i) = y_i.
$$
:::

. . .

**Proof of existence**: Define [Lagrange]{.emph} polynomials
$$
\forall i \in \{0, \dotsc, n\}, \qquad
L_i(x) := \prod_{\substack{j = 0 \\ j \neq i}}^{n} \frac {x - x_j} {x_i - x_j}.
$$
Then set $p(x) = \sum_{i=0}^{n} y_i L_i(x)$ and verify that $p$ is an interpolating polynomial,
which proves existence.

. . .

**Proof of uniqueness**:
assume $q \in \mathcal P_n$ is another interpolating polynomial.
Then $p - q \in \mathcal P_n$ and
$$
    \forall i \in \{0, \dotsc, n\}, \qquad
    p(x) - q(x) = 0.
$$
Thus $p - q$ is a polynomial of degree at most $n$ with $n + 1$ roots, so $p - q = 0$.

## Illustration: Lagrange polynomials {.smaller}

Key property of Lagrange polynomials:
$$
L_i(x_j) =
\begin{cases}
1 & \text{if $i = j$} \\
0 & \text{if $i \neq j$}
\end{cases}
$$

:::: {.columns}

::: {.column width="45%"}
```{julia}
#| echo: true
#| eval: false
#| code-fold: false
#| code-line-numbers: false
using Plots
using LaTeXStrings

# Interpolation nodes
x = [1, 2, 3]

function L(i, z)
    result = 1.0
    for j in 1:length(x)
        if i != j
            result *= (z - x[j]) / (x[i] - x[j])
        end
    end
    return result
end

scatter(x, ones(3), title="Lagrange polynomials")
plot!(legend=:outertopright, size=(900, 900))
plot!(z -> L(1, z), label=L"L_1")
plot!(z -> L(2, z), label=L"L_2")
plot!(z -> L(3, z), label=L"L_3")
```
:::

::: {.column width="5%"}
:::

::: {.column width="45%"}
```{julia}
#| echo: false
#| eval: true
#| code-fold: false
#| code-line-numbers: false
using Plots
using LaTeXStrings

# Interpolation nodes
x = [1, 2, 3]

function L(i, z)
    result = 1.0
    for j in 1:length(x)
        if i != j
            result *= (z - x[j]) / (x[i] - x[j])
        end
    end
    return result
end

scatter(x, ones(3), label="nodes", title="Lagrange polynomials")
plot!(z -> L(1, z), label=L"L_1")
plot!(z -> L(2, z), label=L"L_2")
plot!(z -> L(3, z), label=L"L_3")
plot!(legend=:outertopright)
```
:::
::::

## Interpolation error {.smaller}

::: {.column width="80%"}
::: {.callout-note icon=false}
## Theorem
**Assumptions**

- $u\colon [a, b] \to \mathbf R$ is a $C^{n+1}([a, b])$ function

- $a=x_0< x_1< \dotsc < x_n=b$ are $n+1$ distinct interpolation nodes

- $\widehat u$ interpolates $u$ at $x_0, x_1, \dotsc, x_n$, i.e. $\widehat u(x_i) = u(x_i)$ for all $i ∈ \{0,\dotsc,n\}$

Then, it holds that $\quad ∀\, x ∈ [a,b],\quad ∃\, ξ=ξ(x) ∈ [a,b]$
$$
    e_n(x) := u(x) - \widehat u(x) = \frac{u^{(n+1)}(\xi)}{(n+1)!} (x-x_0) \dotsc (x - x_n)
$$
:::
:::

## Corollary {.smaller}

::: {.column width="80%"}
::: {.callout-note icon=false}
## Theorem
**Assumptions**

- $u\colon [a, b] \to \mathbf R$ is a smooth function

- $a=x_0< x_1< \dotsc < x_n=b$ are $n+1$ distinct interpolation nodes

- $\widehat u$ interpolates $u$ at $x_0, x_1, \dotsc, x_n$.

Then it holds that
$$
    E_n := \sup_{x \in [a, b]} \bigl\lvert e_n(x) \bigr\rvert \leq \frac{C_{n+1}}{4(n+1)} h^{n+1},
    \qquad
    C_{n+1} :=
    \sup_{x \in [a, b]} \left\lvert u^{(n+1)}(x) \right\rvert.
$$
where $h$ is the maximum spacing between two successive interpolation nodes.
:::
:::
\begin{corollary}
    [Upper bound on the interpolation error]
    \label{corollary:interpolation_error}
\end{corollary}

## Chebyshev roots {.smaller}

**Question**? What nodes $(x_0, \dotsc x_n)$ to pick  to minimize $(x-x_0) \dotsc (x - x_n)$? Recall
$$
    u(x) - \widehat u(x) = \frac{u^{(n+1)}(\xi)}{(n+1)!} (x-x_0) \dotsc (x - x_n)
$$

::: {.column width="80%"}
::: {.callout-note icon=false}
## Theorem
Assume that $p$ is a [monic]{.emph} polynomial of degree $n \geq 1$:
$$
    p(x) = \alpha_0 + \alpha_1 x + \dotsb + \alpha_{n-1} x^{n-1} +  x^n.
$$
Then it holds that
$$
    \label{eq:chebychev_lower_bound}
    \sup_{x \in [-1, 1]} \bigl\lvert p(x) \bigr\rvert \geq \frac{1}{2^{n-1}} =: E.
$$
In addition, the lower bound is achieved for $p_*(x) = 2^{-(n-1)} T_n(x)$,
where $T_n$ is the Chebyshev polynomial of degree $n$:
$$
    \label{eq:chebyshev_polynomial}
    T_n(x) = \cos(n\arccos x) \qquad (-1 \leq x \leq 1).
$$
:::
:::

. . .

$\leadsto$ **Idea**: use roots of $T_n$ as interpolation nodes

## Sine function with equidistant nodes {.smaller}

```{julia}
#| echo: false
#| eval: true
#| code-fold: false
#| code-line-numbers: false

using Polynomials

function plotsin(n)
    lims = (0, 2π)
    X = LinRange(0, 2π, n)
    f(x) = sin(x)
    Y = f.(X)
    P = Polynomials.fit(X, Y)
    x_plot = LinRange(lims[1], lims[2], 600)
    Plots.plot(xlims=lims, size=(600,400))
    Plots.plot!(x_plot, f.(x_plot), label="")
    Plots.plot!(x_plot, P.(x_plot), label="")
    Plots.scatter!(X, f.(X), label = "$n nodes", legend=:topright)
    Plots.plot!(xlim = lims, ylim = (-1.2, 1.2))
    Plots.xticks!(range(0,2π,step=π/4), [L"0",L"\frac{π}{4}",L"\frac{π}{2}",L"\frac{3π}{4}",L"π",L"\frac{5π}{4}",L"\frac{3π}{2}",L"\frac{7π}{4}",L"2π"])
end
;
```

:::: {.columns}

::: {.column width="10%"}
:::

::: {.column width="30%"}
$$
u(x)=\sin{x}
$$
$$
x_k=a + (b-a) \frac{k}{n} \quad (0 ≤ k ≤ n)
$$
:::

::: {.column width="10%"}
:::

::: {.column width="40%"}
::: {.fragment .fade-up}
```{julia}
#| echo: false
#| eval: true
#| code-fold: false
#| code-line-numbers: false
plotsin(3)
```
:::
:::

::: {.column width="10%"}
:::

::::

:::: {.columns}

::: {.column width="10%"}
:::

::: {.column width="40%"}
::: {.fragment .fade-up}
```{julia}
#| echo: false
#| eval: true
#| code-fold: false
#| code-line-numbers: false
plotsin(4)
```
:::
:::

::: {.column width="40%"}
::: {.fragment .fade-up}
```{julia}
#| echo: false
#| eval: true
#| code-fold: false
#| code-line-numbers: false
plotsin(8)
```
:::
:::

::: {.column width="10%"}
:::

::::

## Runge function with equidistant nodes {.smaller}

```{julia}
#| echo: false
#| eval: true
#| code-fold: false
#| code-line-numbers: false

function plotRunge(n)
    lims = (-1, 1)
    X = LinRange(-1, 1, n)
    f(x) = 1 / (1 + 25x^2)
    Y = f.(X)
    P = Polynomials.fit(X, Y)
    x_plot = LinRange(lims[1], lims[2], 600)
    Plots.plot(xlims=lims, size=(600,400))
    Plots.plot!(x_plot, f.(x_plot), label="")
    Plots.plot!(x_plot, P.(x_plot), label="")
    Plots.scatter!(X, f.(X), label = "$n nodes", legend=:topright)
    Plots.plot!(xlim = lims)
end
;
```

:::: {.columns}

::: {.column width="10%"}
:::

::: {.column width="30%"}
$$
u(x)=\frac{1}{1+25x^2}
$$
$$
x_k=a + (b-a) \frac{k}{n} \quad (0 ≤ k ≤ n)
$$
:::

::: {.column width="10%"}
:::

::: {.column width="40%"}
::: {.fragment .fade-up}
```{julia}
#| echo: false
#| eval: true
#| code-fold: false
#| code-line-numbers: false
plotRunge(6)
```
:::
:::

::: {.column width="10%"}
:::

::::

:::: {.columns}

::: {.column width="10%"}
:::

::: {.column width="40%"}
::: {.fragment .fade-up}
```{julia}
#| echo: false
#| eval: true
#| code-fold: false
#| code-line-numbers: false
plotRunge(10)
```
:::
:::

::: {.column width="40%"}
::: {.fragment .fade-up}
```{julia}
#| echo: false
#| eval: true
#| code-fold: false
#| code-line-numbers: false
plotRunge(20)
```
:::
:::

::: {.column width="10%"}
:::

::::

## Optimization of the nodes: Chebyshev nodes {.smaller}

```{julia}
#| echo: false
#| eval: true
#| code-fold: false
#| code-line-numbers: false

function plotRungeCheb(n)
    lims = (-1, 1)
    k = 0:(n-1)
    X = @. -cos(π*(k+1/2)/n)
    f(x) = 1 / (1 + 25x^2)
    Y = f.(X)
    P = Polynomials.fit(X, Y)
    x_plot = LinRange(lims[1], lims[2], 600)
    Plots.plot(xlims=lims, size=(600,400))
    Plots.plot!(f, x_plot, label="")
    Plots.plot!(f, x_plot, label="")
    Plots.scatter!(X, f.(X), label = "$n nodes", legend=:topright)
    Plots.plot!(xlim = lims)
end
;
```

**Idea:** Take $x_0 < x_1 < \dotsc < x_n$ to be the roots of $T_n$:

$$
x_k=-\cos \Bigl(\pi \frac{k + \frac{1}{2}}{n} \Bigl),
\qquad (0 ≤ k < n)
$$

:::: {.columns}


::: {.column width="49%"}
::: {.fragment .fade-up}
```{julia}
#| echo: false
#| eval: true
#| code-fold: false
#| code-line-numbers: false
plotRungeCheb(15)
```
:::
:::

::: {.column width="49%"}
::: {.fragment .fade-up}
```{julia}
#| echo: false
#| eval: true
#| code-fold: false
#| code-line-numbers: false
plotRungeCheb(30)
```
:::
:::
::::

## Piecewise interpolation {.smaller}

:::: {.columns}

::: {.column width="10%"}
:::

::: {.column width="80%"}
::: {.callout-note icon="false"}
## Piecewise continuous interpolation
Let $e_n$ denote the interpolation error and recall that
\begin{align}
    &\max_{x ∈ [a, b]} \bigl\lvert e_n(x) \bigr\rvert \leq \frac{C_{n+1}}{4(n+1)} h^{n+1},
    \qquad
    C_{n+1} = \max_{x ∈ [a, b]} \left\lvert u^{(n+1)}(x) \right\rvert
\end{align}
with $h = \max_{i ∈ \{0, \dotsc, n-1\}} \lvert x_{i+1} - x_i\rvert$


Idea to control the error :

  - Divide interval $[a,b]$ into $n$ subinteravl of size $h=\frac{b-a}{n}$

  - Interpolate with a polynomial of degree $m$ over $[x_{i},x_{i+1}]$

    ```{julia}
    #| echo: false
    #| eval: true
    #| code-fold: false
    #| code-line-numbers: false

    δ = 0.2
    pl = Plots.plot(size = (700,100), ylim =(-δ,δ))
    xs = LinRange(-1, 1, 37)
    Plots.plot!(xs, zero(xs),)
    Plots.scatter!(xs, zero(xs), markersize=6, markershape=:diamond,)
    xs = LinRange(-1, 1, 13)
    Plots.scatter!(xs, zero(xs), markersize=8,)
    Plots.plot!(axis = false, grid = false, legend = false, ticks = false)
    ```
    $$
    \max_{x ∈ [x_{i},x_{i+1}]} \bigl\lvert e_n(x) \bigr\rvert \leq \frac{C_{m+1}}{4(m+1)} \left(\frac{h}{m}\right)^{m+1}
    \quad \Rightarrow \quad
    \max_{x ∈ [a, b]} \bigl\lvert e_n(x) \bigr\rvert \leq \frac{C_{m+1}}{4(m+1)} \left(\frac{h}{m}\right)^{m+1}
    $$

  - $m$ is fixed and small but $h$ can vary.
    The error scales as $C h^{m+1}$.

:::
:::
::::

## Example (1/3)

```{julia}
#| echo: false
#| eval: true
#| code-fold: false
#| code-line-numbers: false
using Plots
using Polynomials
f(x) = 1 / (1 + 10*(x+.5cos(4x))^2)

function plot_n_m(n, m)
    X = -1:2/n:1
    x = -1:2/(n*m):1
    xplot = LinRange(-1, 1, 200)
    pl = plot(title="n = $n, m = $m", size=(1200, 700))
    plot!(f, xplot, linewidth=2, label="f(x)")
    scatter!(f, x, markersize=4, label=nothing)
    scatter!(f, X, markersize=8, label=nothing)
    vline!(X, color="gray", xlims=(-1, 1), label=nothing)
    for i in 1:n
        a, b = -1 + 2(i-1)/n, -1 + 2i/n
        x_interp = LinRange(a, b, m + 1)
        x_fine = LinRange(a, b, 50)
        p = fit(x_interp, f.(x_interp))
        plot!(x_fine, p.(x_fine), label=nothing)
    end
    return pl
end

plot_n_m(3, 2)
```

## Example (2/3)

```{julia}
#| echo: false
#| eval: true
#| code-fold: false
#| code-line-numbers: false
plot_n_m(4, 3)
```


## Example (3/3)

```{julia}
#| echo: false
#| eval: true
#| code-fold: false
#| code-line-numbers: false
plot_n_m(8, 3)
```

## Least squares approximation {.smaller}

:::: {.columns}

::: {.column width="80%"}
::: {.callout-note icon="false"}
## Problem statement
- $n+1$ distinct nodes $a=x_0< x_1< \dotsc < x_n=b$

- $n+1$ values $u_0, u_1, \dotsc, u_n$

- a vector space ${\rm Span}(φ_0,φ_1,\dotsc,φ_m)$ of continuous functions on $[a,b]$ 
  with $\color{red}{m<n}$

We wish to find 
$\widehat u(x) = α_0 φ_0(x) + \dotsb + α_m φ_m(x)$
such that
$$
\forall i \in \{0, \dotsc, n\}, \qquad
    \widehat u(x_i) \, {\color{red}{\approx}} \, u_i
$$
Matrix form of these equations:
$$
\mat A \vect \alpha :=
\begin{pmatrix}
    \varphi_0(x_0) & \varphi_1(x_0) & \dots & \varphi_m(x_0) \\
    \varphi_0(x_1) & \varphi_1(x_1) & \dots & \varphi_m(x_1) \\
    \varphi_0(x_2) & \varphi_1(x_2) & \dots & \varphi_m(x_2) \\
    \vdots & \vdots & & \vdots \\
    \varphi_0(x_{n-2}) & \varphi_1(x_{n-2}) & \dots & \varphi_m(x_{n-2}) \\
    \varphi_0(x_{n-1}) & \varphi_1(x_{n-1}) & \dots & \varphi_m(x_{n-1}) \\
    \varphi_0(x_n) & \varphi_1(x_n) & \dots & \varphi_m(x_n)
\end{pmatrix}
\begin{pmatrix}
    \alpha_0 \\
    \alpha_1 \\
    \vdots \\
    \alpha_m
\end{pmatrix}
{\color{red}{\approx}}
\begin{pmatrix}
    u_0 \\
    u_1 \\
    u_2 \\
    \vdots \\
    u_{n-2} \\
    u_{n-1} \\
    u_n
\end{pmatrix} =: \vect b
$$
:::
:::
::::

## Solution via minimization problem

:::: {.columns}

::: {.column width="65%"}
::: {.callout-note appearance="minimal"}
**Key idea**: Minimize
$$
J(\vect \alpha)=
\frac{1}{2}\,\sum_{i=0}^{n} \abs{\widehat u(x_i) - u_i}^2
= \frac{1}{2}\,\sum_{i=0}^{n} \left( \sum_{j=0}^{m} \alpha_j \varphi_j(x_i) - u_i\right)^2
=\frac{1}{2}\,\norm{\mat A \vect \alpha-\vect b}^2
$$

To this end, we seek $\alpha$ such that
$$
\nabla J(\vect \alpha)=\frac{1}{2}\,\nabla \Bigl( (\mat A \vect \alpha - \vect b)^\t (\mat A \vect \alpha - \vect b) \Bigr)=\vect 0,
$$
which leads to the equation
$$
\nabla J(\vect \alpha)=\mat A^\t (\mat A \vect \alpha - \vect b)
=\vect 0
$$
Rearranging, we obtain the following [linear system]{.emph}
$$
\mat A^\t \mat A \vect \alpha = \mat A^\t \vect b.
$$
:::
:::

::: {.column width="30%"}
::: {.fragment .fade-up}
::: {.callout-tip icon="false"}
## Remark
In `Julia`, the result of the caluclation $\alpha=(\mat A^\t \mat A)^{-1} \mat A^\t \vect b$ can be obtained via
```{julia}
#| echo: true
#| eval: false
#| code-fold: false
#| code-line-numbers: false
α = A\b
```
:::
:::
:::

::::

## [`Polynomials.jl`](https://github.com/JuliaMath/Polynomials.jl) library {.smaller}

:::: {.columns}

::: {.column width="50%"}
- Github repository <https://github.com/JuliaMath/Polynomials.jl>

- Documentation <https://juliamath.github.io/Polynomials.jl/stable/>

<iframe src="https://juliamath.github.io/Polynomials.jl/stable/" width="100%" height="600" data-external="1">
</iframe>
:::

::: {.column width="50%"}
Example use of [`fit`](https://juliamath.github.io/Polynomials.jl/stable/#Fitting-arbitrary-data)
```{julia}
#| echo: true
#| eval: true
#| code-fold: false
#| code-line-numbers: false

using Plots, Polynomials
xs = range(0, 10, length=10)
ys = @. exp(-xs)
f1 = fit(xs, ys) # degree = length(xs) - 1
f2 = fit(xs, ys, 2) # degree = 2

scatter(xs, ys, label="Data")
plot!(f1, extrema(xs)..., label="Fit")
plot!(f2, extrema(xs)..., label="Quadratic Fit")
width, height = 750, 500 ; plot!(size = (width, height), legend = :topright)
```
:::
::::

